[book]
authors = ["steveonlinux"]
language = "en"
multilingual = false
src = "src"
title = "Stephen Mark's Personal Website"

[output.html]
additional-css = ["custom.css"]
mathjax-support = true
no-section-label = true

